version: "3.7"

services:
  mongo:
    image: mongo:7.0
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: flatsDB
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data:/data/db
      - ./onBuild/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
